#!/usr/bin/env python3
"""Generate conformance report markdown from the test runner's JSON output.

Usage:
    cargo run -p aris-render --features "desktop winit js" --bin conformance_test > /tmp/results.json
    python scripts/conformance/report.py /tmp/results.json > docs/guides/conformance-report.md

Or combined:
    just conformance-report
"""

import json
import sys
from collections import defaultdict


def main():
    if len(sys.argv) < 2:
        print("Usage: report.py <results.json>", file=sys.stderr)
        sys.exit(1)

    with open(sys.argv[1]) as f:
        data = json.load(f)

    tests = data["tests"]
    by_category = defaultdict(list)
    for t in tests:
        by_category[t["category"]].append(t)

    total = len(tests)
    passed = sum(1 for t in tests if t["status"] == "pass")
    failed = total - passed

    lines = []
    lines.append("# aris Conformance Report\n")
    lines.append(f"> Auto-generated by `scripts/conformance/report.py`.\n")
    lines.append(f"> **Total: {total}** | **Pass: {passed}** | **Fail: {failed}** | **Pass rate: {passed * 100 // max(total, 1)}%**\n")
    lines.append("")

    for category in sorted(by_category.keys()):
        cat_tests = by_category[category]
        cat_pass = sum(1 for t in cat_tests if t["status"] == "pass")
        cat_total = len(cat_tests)
        lines.append(f"## {category} ({cat_pass}/{cat_total})\n")
        lines.append(f"| Test ID | Status | Description | Detail |")
        lines.append(f"|---------|--------|-------------|--------|")
        for t in cat_tests:
            icon = "✅" if t["status"] == "pass" else "❌"
            lines.append(f"| `{t['id']}` | {icon} {t['status']} | {t['description']} | {t['detail']} |")
        lines.append("")

    print("\n".join(lines))


if __name__ == "__main__":
    main()
