#!/usr/bin/env python
"""Generate WPT conformance report from wpt_runner JSON output.

Usage:
    RUST_LOG="" cargo run -p aris-render --features "desktop winit js" --bin wpt_runner -- tests/wpt/wpt-master/dom > results.json
    python scripts/conformance/wpt_report.py results.json > docs/guides/wpt-report.md
"""

import json
import sys
from collections import defaultdict


def main():
    if len(sys.argv) < 2:
        print("Usage: wpt_report.py <results.json>", file=sys.stderr)
        sys.exit(1)

    with open(sys.argv[1], encoding="utf-8") as f:
        data = json.load(f)

    results = data["results"]
    by_dir = defaultdict(lambda: {"files": 0, "tests": 0, "pass": 0, "fail": 0, "skip": 0, "crash": 0})

    for r in results:
        # Group by first directory component.
        parts = r["file"].replace("\\", "/").split("/")
        category = parts[0] if len(parts) > 1 else "root"
        d = by_dir[category]
        d["files"] += 1
        d["tests"] += r.get("tests", 0)
        d["pass"] += r.get("pass", 0)
        d["fail"] += r.get("fail", 0)
        status = r.get("status", "skip")
        if status == "skip":
            d["skip"] += 1
        elif status == "crash":
            d["crash"] += 1

    total = data["total_tests"]
    passed = data["total_pass"]
    failed = data["total_fail"]
    rate = data["pass_rate"]

    lines = []
    lines.append("# aris W3C Web-Platform-Tests Report\n")
    lines.append(f"> Auto-generated by `scripts/conformance/wpt_report.py`.\n")
    lines.append(f"> **Tests: {total}** | **Pass: {passed}** | **Fail: {failed}** | **Pass rate: {rate}%**\n")
    lines.append(f"> Source: `web-platform-tests` (real W3C test suite)\n")
    lines.append("")

    lines.append("## Summary by Category\n")
    lines.append("| Category | Files | Tests | Pass | Fail | Pass Rate |")
    lines.append("|----------|-------|-------|------|------|-----------|")
    for cat in sorted(by_dir.keys()):
        d = by_dir[cat]
        r = (d["pass"] * 100 // max(d["tests"], 1)) if d["tests"] > 0 else 0
        lines.append(f"| {cat} | {d['files']} | {d['tests']} | {d['pass']} | {d['fail']} | {r}% |")
    lines.append("")

    lines.append("## Passing Tests\n")
    lines.append("| File | Pass | Tests |")
    lines.append("|------|------|-------|")
    for r in sorted(results, key=lambda x: -x.get("pass", 0)):
        if r.get("pass", 0) > 0:
            lines.append(f"| `{r['file']}` | {r['pass']} | {r.get('tests', 0)} |")
    lines.append("")

    lines.append("## Top Failing Tests\n")
    lines.append("| File | Fail | Tests |")
    lines.append("|------|------|-------|")
    top_fails = sorted(
        [r for r in results if r.get("fail", 0) > 0],
        key=lambda x: -x.get("fail", 0),
    )[:30]
    for r in top_fails:
        lines.append(f"| `{r['file']}` | {r['fail']} | {r.get('tests', 0)} |")
    lines.append("")

    print("\n".join(lines))


if __name__ == "__main__":
    main()
